//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement.Shared.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EventManagement.Shared.Localizations.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument can&apos;t be null.
        /// </summary>
        public static string ArgumentNull {
            get {
                return ResourceManager.GetString("ArgumentNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndDate must be greather than StartDate.
        /// </summary>
        public static string DatesException {
            get {
                return ResourceManager.GetString("DatesException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event is already marked as Active.
        /// </summary>
        public static string EventAlreadyMarkedAsActive {
            get {
                return ResourceManager.GetString("EventAlreadyMarkedAsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event was already marked as Archived.
        /// </summary>
        public static string EventAlreadyMarkedAsArchived {
            get {
                return ResourceManager.GetString("EventAlreadyMarkedAsArchived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event can&apos;t be edited by this user.
        /// </summary>
        public static string EventEditConflict {
            get {
                return ResourceManager.GetString("EventEditConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event can&apos;t be edited anymore.
        /// </summary>
        public static string EventNotEditable {
            get {
                return ResourceManager.GetString("EventNotEditable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event not found.
        /// </summary>
        public static string EventNotFound {
            get {
                return ResourceManager.GetString("EventNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with this email already exists.
        /// </summary>
        public static string ExistingEmail {
            get {
                return ResourceManager.GetString("ExistingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password is incorrect.
        /// </summary>
        public static string IncorrectCredentials {
            get {
                return ResourceManager.GetString("IncorrectCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded file has invalid file name.
        /// </summary>
        public static string InvalidFileName {
            get {
                return ResourceManager.GetString("InvalidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tickets remaining for this event.
        /// </summary>
        public static string NoAvailableTickets {
            get {
                return ResourceManager.GetString("NoAvailableTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EventFilePath is not configured correctly.
        /// </summary>
        public static string PhotoPathException {
            get {
                return ResourceManager.GetString("PhotoPathException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already has a reserved ticket.
        /// </summary>
        public static string TicketAlreadyReserved {
            get {
                return ResourceManager.GetString("TicketAlreadyReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has no roles.
        /// </summary>
        public static string UserHasNoRoles {
            get {
                return ResourceManager.GetString("UserHasNoRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User could not be found.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
    }
}
